### ISSUE TITLE
Updating datasets for all assets

### ISSUE THREAD

**Issue by nelohenriq** [dcaribou/transfermarkt-scraper#30]
I've created a venv in anaconda like we can see in the image below
![Anaconda](https://user-images.githubusercontent.com/4016200/134583814-75743584-5d43-4429-b871-cacc020dc1d0.png)

Next i open a terminal from the anaconda environments tab
![Anaconda_1](https://user-images.githubusercontent.com/4016200/134583935-634283e8-d18a-426c-af39-7f0048ec1bf3.png)

When i run the first scrapy crawl it gives no errors but the file confederations.json its empty
![scrapy](https://user-images.githubusercontent.com/4016200/134584093-55015730-1b94-44a2-a090-9c0aa2933683.png)

Then i run the competitions command and again no errors
![scrapy_1](https://user-images.githubusercontent.com/4016200/134584385-85868e7e-eab5-46dc-a943-8f7d82e98038.png)

But again and empty competitions.json file is created

What am i doing wrong?

**Comment by dcaribou** [comment]
Hey @nelohenriq. I think what you are missing here is to provide the user agent for your crawling. Please, note this section in the README.

> ⚠️ When using this scraper please identify your project accordingly by using a custom user agent. You can pass the user agent string using the `USER_AGENT` scrapy setting. For example, `scrapy crawl players -s USER_AGENT=<your user agent>`

You should probably cleanup the scrapy cache as well, since you've already run it without the `USER_AGENT` setting. You can do this by removing the `.scrapy` folder that was created in the project root or run it without caching using the setting `-s HTTPCACHE_ENABLED=False`

Finally, you can find some more tips about how to get started with the scraper in [this](https://github.com/dcaribou/transfermarkt-scraper/issues/28) other issue as well.

**Comment by nelohenriq** [comment]
I tried to run with the USER_AGENT tag but the result is the same, empty files

This is the content of the file created

```
Scrapy 2.4.1 - no active project

Unknown command: crawl

Use "scrapy" to see available commands
```

**Comment by dcaribou** [comment]
Oh, I see. This message means that you are missing the necessary python modules to run the project in your environment. Have you installed and activated the environment as [described in the README](https://github.com/dcaribou/transfermarkt-scraper#run)?

**Comment by nelohenriq** [comment]
Yes David, as you can see on the images on my first issue post, i imported the environment.yml into anaconda, so the requirements present on the requirements.txt file should be satisfied on install, or am i wrong?

**Comment by dcaribou** [comment]
Right. How did you import the `environment.yml` in anaconda? From the command line, I usually follow [this](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file) instructions, but I've never done it from the UI.

Where you able to verify that the packages are installed in your environment? It seems that the UI provides a list of packages installed (I can see it in your screenshots)

On the docker option, what is the error that you are getting?

Anyways, if all you need is to get the files updated, the published datasets in [Kaggle](https://www.kaggle.com/davidcariboo/player-scores) and [data.world](https://data.world/dcereijo/player-scores) are updated automatically once a week. Maybe that is enough for your purposes?

**Comment by dcaribou** [comment]
Hey @nelohenriq. Are there any news on this? Did you manage to get the scraper working?

**Comment by R0hm** [comment]
I had the same problem with a different setup (creating the conda env with the environment.yml from a fresh Pycharm project), but supplying a USER_AGENT did solve it.

Was it bugging because without that, the requests are send without any user_agent field and transfermarkt requires one ?

Anyway, this project looks super clean and well done and I'll try to improve my scrapy skill exploring it, so thanks a lot 👍

**Comment by dcaribou** [comment]
I'm glad to know that passing the USER_AGENT solved it for you @R0hm.

> Was it bugging because without that, the requests are send without any user_agent field and transfermarkt requires one ?

I think the problem is that transfermarkt rejects requests from user agents that contain the string "scrap", which is the case of the default scrapy user agent, hence a different user agent (without the string "scrap" needs to be provided). Also, I feel it's fair to roughly identify your scraper, considering your are going to hit their servers with a few thousand requests 😄 

> Anyway, this project looks super clean and well done and I'll try to improve my scrapy skill exploring it, so thanks a lot 👍

I appreciate it @R0hm. Good luck with the exploration, feel free to reach out if you need help.
